#!/bin/sh

# Define the argument list
ARG="42 17 -8 23 91 -34 56 3 -12 88 76 45 -27 19 67 -99 31 5 73 81 -44 22 -6 90 12 53 28 -50 66 11"

if [ "$1" = "debug" ]; then
    # Run with additional debug flags
    gdb --args ./push_swap $ARG
else
    # Run without debug flags
    ./push_swap $ARG
fi
